name: CI - Firebase Auth and Unit Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-firebase-auth:
    runs-on: ubuntu-latest

    env:
      FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}
      FIREBASE_PROJECT_ID: demo-firebase

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Install Firebase CLI
        run: npm install -g firebase-tools@latest

      - name: Start Firebase Authentication Emulator
        run: |
          nohup firebase emulators:start --only auth > /dev/null &
          sleep 5

      - name: Clear Jest Cache
        run: npx jest --clearCache

      - name: Install Babel CLI
        run: npm install --save-dev @babel/cli
      
      - name: Check Babel Configuration
        run: |
          npx cross-env BABEL_SHOW_CONFIG_FOR=frontend/SCNA/_test_/auth.test.js npx babel --version

      - name: Run Firebase Authentication Tests
        run: |
          echo "$FIREBASE_CREDENTIALS" > firebase-credentials.json
          export GOOGLE_APPLICATION_CREDENTIALS=firebase-credentials.json
          npx jest --ci --testPathPattern "_test_"

  test-all-unit-tests:
    runs-on: ubuntu-latest
    needs: test-firebase-auth

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Clear Jest Cache
        run: npx jest --clearCache

      - name: Run All Unit Tests
        run: npx jest --ci --coverage
