name: CI - Firebase Auth and Unit Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-firebase-auth:
    runs-on: ubuntu-latest

    env:
      FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}
      FIREBASE_PROJECT_ID: demo-firebase

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Dependencies
        run: |
          cd frontend/SCNA
          npm install
          npm install @react-native-firebase/auth --save

      - name: Install Firebase CLI
        run: |
          cd frontend/SCNA
          npm install -g firebase-tools@latest

      - name: Start Firebase Authentication Emulator
        run: |
          cd frontend/SCNA
          nohup firebase emulators:start --only auth > /dev/null &
          sleep 5

      - name: Clear Jest Cache
        run: |
          cd frontend/SCNA
          npx jest --clearCache

      - name: Run Firebase Authentication Tests
        run: |
          cd frontend/SCNA
          echo "$FIREBASE_CREDENTIALS" > firebase-credentials.json
          export GOOGLE_APPLICATION_CREDENTIALS=firebase-credentials.json
          npx jest --ci --config jest.config.js --testPathPattern "_test_"

  test-all-unit-tests:
    runs-on: ubuntu-latest
    needs: test-firebase-auth

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Dependencies
        run: |
          cd frontend/SCNA
          npm install

      - name: Clear Jest Cache
        run: |
          cd frontend/SCNA
          npx jest --clearCache

      - name: Run All Unit Tests
        run: |
          cd frontend/SCNA
          npx jest --ci --coverage
